日付検索で カスタムフィールド参照&カスタムフィールド名未指定 の場合の処理を調整
vektor-inc/vk-dynamic-if-block pull request #40
Opened 2023-08-17 00:35 UTC by osmdik

https://github.com/vektor-inc/vk-dynamic-if-block/issues/39

- [ ] カスタムフィールドの値が未入力の場合 -> 表示
- [ ] カスタムフィールドが未入力の場合は「参照するカスタムフィールド名を入力してください」のアラートを表示
- [ ] カスタムフィールドに入力された値が日付のフォーマットじゃない値だった場合 -> 表示

2023-08-17 16:17 UTC, kurudrive commented
@osmdik ありがとうございます。PHPUnitテストの追加をよろしくお願いいたします。

2023-08-18 01:23 UTC, kurudrive commented on tests/test-dynamic-if.php
> +				'name'      => 'Display Period [ deadline / referCustomField / not date]( true )',
@osmdik こう？
```suggestion
				'name'      => 'Display Period [ daysSincePublic / referCustomField / not date]( true )',
```

2023-08-18 02:19 UTC, kurudrive requested changes

2023-08-18 02:19 UTC, kurudrive commented on src/editor.scss
> +.alert {
@osmdik .alert  について通常の本文エリアでテーマなどで指定された .alert が使われてると干渉したりする可能性があるので、サイドパネルにクラス名つけて、そのクラス名を .alert の前に追加するか、.vkdif__alert みたいにプリフィックスをつけるなどしてください (￣人￣)

2023-08-18 04:32 UTC, osmdik commented
@kurudrive 
失礼しました。テストの修正とalertのスタイル用のクラス名を追加したので、
また確認をお願い致します。

2023-08-20 23:18 UTC, kurudrive commented
@osmdik アラート表示調整よろしくお願いいたします  (￣人￣)
![スクリーンショット 2023-08-18 19 59 43](https://github.com/vektor-inc/vk-dynamic-if-block/assets/3272660/ddad63ec-817d-4d39-8626-219ec61a0f6d)

2023-08-20 23:26 UTC, kurudrive commented
@osmdik ↓もよろしくお願いいたします (￣人￣)

```
		"displayPeriodSetting": {
			"type": "string",
			"default": "none"
		},
		"periodSpecificationMethod": {
			"type": "string",
			"default": "direct"
		},
		"displayPeriodValue": {
			"type": "string",
			"default": ""
		},
		"referCustomFieldName": {
			"type": "string",
			"default": ""
		}
```

最後 referCustomFieldName だと、どの条件分岐のためのカスタムフィールド参照かわからないので変更したいです。
で、条件分岐のための設定値だという事がわかりやすいように
periodDisplaySetting
periodSpecificationMethod
periodDisplayValue
periodReferCustomField
に変更するか
period の中に配列で4つの値をもたせるかに変更してください。
※ この機能自体幸いまだリリースしてないので depricated などは不要

2023-08-21 01:37 UTC, osmdik commented
@kurudrive 
それぞれ調整したので、また確認をおねがいいたします。

2023-08-21 02:43 UTC, kurudrive approved these changes

2023-08-21 02:47 UTC, kurudrive commented
@osmdik  ありがとうございました。

2023-08-21 02:55 UTC, merged