【二人目確認中】ログインユーザーにのみ表示されるオプションを追加
vektor-inc/vk-dynamic-if-block pull request #48
Opened 2024-02-01 07:17 UTC by osmdik

## チケットへのリンク / 変更の理由（元のissueがあればリンクを貼り付ければOK）
https://github.com/vektor-inc/vk-dynamic-if-block/issues/47

## このプルリクで変更した事の概要

ログインユーザーにのみコンテンツを表示するオプションを追加しました。

## 実装者の確認事項

実装者はレビュワーに回す前に以下の事を確認してチェックをつけてください。

#### ソースコードについて

- [x] 複数の意図の変更 （ 機能の不具合修正 + 別の機能追加など ） を含んでいないか？
- [x] 関数名 / 変数名 / クラス名 / 保存値名 はそれだけで内容が想像できるものになっているか？紛らわしい命名になっていないか？
- [x] 関数名 / 変数名 / クラス名 / 保存値名 は既存のコードの命名規則に沿ったものになっているか？

#### デザイン・UI

- [ ] 初見のユーザーが予備知識無しで使っても使いやすいようになっているか？
- [ ] 情報意味を考慮した意味グルーピング・余白になっているか？
- [ ] アラートの表示など追加した場合は他の同様の表示と同じデザインになっているか？

#### プログラムの変更の場合

テストを書かないのは普通ではありません。書けるテストは極力書くようにしてください。
書いていない場合は書かない理由を記載してください。

- [x] 書けそうなテストは書いたか？

#### その他

- [x] readme.txt に変更内容は書いたか？
- [x] Files changed (変更ファイル)の内容は目視でちゃんと確認したか？
- [x] このチェック項目を機械的にチェックするのではなく本当にちゃんと確認をしたか？

## 変更内容について何を確認したか、どういう方法で確認をしたかなど

実装者が確認した手順を箇条書きで記載してください。

- 特に何も設定しない場合、表示されることを確認
- 機能をtrueにした場合、ログインしている場合にのみ表示されることを確認
- `npm run phpunit`が通ることを確認

機能追加になるので石川さん + もう一人 の確認をお願いします。

- [x] 上記記載の手順で初見の人は本当に手順が再現できるか？

## レビュワーに回す前の確認事項

- [x] 実装者はこのテンプレートのチェック項目をちゃんと確認してチェックしたか？

## 実装者が確認した手順以外でレビュワーに確認して欲しい事項など

---

## レビュワー向け

### レビュワーが確認して変更が反映されていない場合の確認事項

レビューしてみて意図した動作をしない場合は再度ビルドするなど以下の項目を確認してください。

* プルしたか？
* ビルドしたか？
* ビルドしたディレクトリは正しいか（別の開発環境のディレクトリを見ていないか）？
* npm install したか？
* composer install したか？
* キャッシュをクリアして確認したか？

2024-02-02 09:51 UTC, kurudrive requested changes

2024-02-02 09:51 UTC, kurudrive commented on src/index.js
> +								'ログインユーザーにのみ表示',
```suggestion
								'Displayed only for logged-in users.,
```

2024-02-02 09:52 UTC, kurudrive commented
@osmdik ありがとうございます。正常に動作確認しました。
二人目誰かよろしくお願いいたします。

2024-02-05 01:00 UTC, sysbird approved these changes

2024-02-05 01:03 UTC, sysbird commented
確認しました
この機能ほしかったんですよ、ありがとうございます
マージしますね

2024-02-05 01:03 UTC, merged